### ISSUE TITLE
Form with remote = true still being processed as text/html

### ISSUE THREAD

**Issue by archonic** [JangoSteve/remotipart#118]
Rails 3.1.10. The includes are working - this is in the head:

    ...
    <script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script>
    <script src="/assets/jquery.iframe-transport.js?body=1" type="text/javascript"></script>
    <script src="/assets/jquery.remotipart.js?body=1" type="text/javascript"></script>
    ...

I have remote => true in the form_for:

     <%= form_for(@attachment, :remote => true, :html => { :multipart => true }) do |f| %>

This is the output for that form:

    <form accept-charset="UTF-8" action="/attachments" class="new_attachment" data-remote="true" enctype="multipart/form-data" id="new_attachment" method="post">

Yet the controller is still interpreting the format as text/html.

    Started POST "/attachments" for 192.168.1.1 at 2014-11-14 14:26:13 -0800
    Processing by AttachmentsController#create as HTML

Any idea what could be happening here?

**Comment by jamesmacwilliam** [comment]
did you ever find an answer for this?

**Comment by Jake0oo0** [comment]
If anyone else is having this issue, try adding ```format: :js``` or ```format: :json``` depending on what you want the response to be.

**Comment by tjaklitsch** [comment]
@archonic did you ever figure this out?

**Comment by archonic** [comment]
I abandoned the gem, but Jake is right. You just need to specifically request and specify a json or js request and response.
