### ISSUE TITLE
All parameters being serialized in #create form processed as JS

### ISSUE THREAD

**Issue by reconstructions** [JangoSteve/remotipart#134]
I can't get Remotipart 1.2.1 to work with edge Rails 4.2.2.  I have tried both the 3.1.4 and 4.0.5 versions of `jquery-rails` and am getting the same error with both versions.  The error seems very similar to this one:

https://github.com/JangoSteve/remotipart/issues/48

If my 'file_field' has a file assigned, all my form parameters appear to be getting serialized like this:
```
Parameters: {"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>nil}}}}}}}}}}}}}}}}}
```
My `remote: true` form is being processed as JS, I am calling a #create action which works fine, with correct parameters, as long I don't have a file assigned to my `file_field`.  The form works fine when processed for an HTML response.  When I assign a file to my `file_field`, then my params are borked as above.

I have carefully worked through the recommended solutions concerning compatibility but with no luck.  I have this in my `application.js`:
```
//= require jquery
//= require jquery_ujs
//= require jquery.remotipart
```
Not sure whether this is a problem with my configuration, my usage, or a bug.  Pretty sure that I have followed all the documented steps, however.

**Comment by ltk** [comment]
For the record, I encountered this same problem. The issue turned out to be a different copy of jquery.iframe-transport.js in my vendor directory that unbeknownst to me was loaded preferentially over remotipart's copy.
