### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by skinofstars** [JangoSteve/remotipart#138]
Can we have a new release please, so we can use the remotipartComplete

**Comment by vala** [comment]
@JangoSteve @mshibuya is there someone who can release a new version of the gem to rubygems ? This would allow us to depend on it in gems

**Comment by mshibuya** [comment]
I've also pinged to @JangoSteve, but no luck so far...

**Comment by vala** [comment]
Well thanks for your feedback @mshibuya, I went with a custom FormData solution instead which covers my needs.

**Comment by JangoSteve** [comment]
Sorry for the delays, everyone. @mshibuya should be able to do a release now 😃

**Comment by mshibuya** [comment]
Thank you @JangoSteve , just pushed v1.3.0 🎉

**Comment by JangoSteve** [comment]
Awesome, thanks @mshibuya 👍
