### ISSUE TITLE
Rails 5 + remotipart not working

### ISSUE THREAD

**Issue by francesco-loreti** [JangoSteve/remotipart#139]
If I use the gem of remotepart 1.2 and I start the application on windows, I have this error:
"C:/Ruby22/lib/ruby/gems/2.2.0/bundler/gems/rails-2b90048395ad/actionpack/lib/action_dispatch/middleware/stack.rb:108:in `assert_index': No such middleware to insert after: ActionDispatch::ParamsParser (RuntimeError) ".
Any solution?

I have tried with github master branch but I have same problem.
Thanks

**Comment by utkukaynar** [comment]
Same problem here.

**Comment by AndreasWurm** [comment]
you could temporarily use gem 'remotipart', github: 'mshibuya/remotipart', ref: '3a6acb3'

**Comment by jasonivers** [comment]
There is a pull request for this... please merge https://github.com/JangoSteve/remotipart/pull/151

**Comment by colinyoung** [comment]
Agreed @JangoSteve, would love to have this merged esp. now that Rails 5 is released.

**Comment by mahemoff** [comment]
@AndreasWurm I think the ref should be 88d9a7 (https://github.com/mshibuya/remotipart/commit/88d9a7d55bde66acb6cf3a3c6036a5a1fc991d5e).

`gem 'remotipart', github: 'mshibuya/remotipart', ref: '88d9a7'`

**Comment by mshibuya** [comment]
88d9a7d55bde66acb6cf3a3c6036a5a1fc991d5e is in the master now.

**Comment by joshkestenberg** [comment]
Hey @mshibuya Master still breaks my code! I'm using your fix `gem 'remotipart', github: 'mshibuya/remotipart', ref: '88d9a7'` and it's working now. If I just use `gem 'remotipart', '~>1.2'` as per the readme, when i try to access any part of my app i get this error `ActionView::Template::Error: ActionView::Helpers::ControllerHelper#params delegated to controller.params, but controller is nil:` followed by like a thousand lines of error msg, and a generic error msg in the console.

**Comment by mshibuya** [comment]
README is old, the latest version is 1.4.2 now.
Just use `gem 'remotipart'` in your Gemfile.

**Comment by joshkestenberg** [comment]
1.4.2 actually isn't working either (`gem 'remotipart'`). Only `88d9a7` has worked so far.

**Comment by mshibuya** [comment]
Your issue appears to be #194, not this.
