### ISSUE TITLE
Rails 3 Missing Body Request Issue 

### ISSUE THREAD

**Issue by mvelikov** [JangoSteve/remotipart#142]
Hello there,

I am using remotipart in a Rails 3 application. 
**Somehow** I receive HTTP requests without body. This is a mystery on its own. The result when I receive such a request is that:
`params = Rack::Request.new(env).params` in remotipart/middleware.rb#12 crashes.

> TypeError POST /welcome/index
> no implicit conversion of nil into Hash

 Although the issue is not in remotipart it could be fixed easily here.

Here is a HTTP sample request that causes this issue:
```
Content-Type: multipart/form-data; charset=utf-8; boundary=------------------------1ABC2DEF3GHI
Accept-Encoding: gzip, deflate
X-Forwarded-Proto: https 
User-Agent: Application/123456 (iPad; iOS 9.2.1; Scale/2.00) 
Accept: */* 
Accept-Language: en-au 
Version: HTTP/1.1
```

On Rails 4 this issue is fixed and the system response with `Server Error 500: bad content body` error.

I recreated this issue in a brand new Rails 3 application only adding _remotipart_ so this is not cause by other third-party gems that I use.

**Comment by mshibuya** [comment]
#143 is already merged, closing.
