### ISSUE TITLE
Rails 5 + remotipart: generates alias_method_chain deprecation

### ISSUE THREAD

**Issue by siruguri** [JangoSteve/remotipart#144]
The pattern for `alias_method_chain` has to be redone in here:

`lib/remotipart/render_overrides.rb`

Using remotipart (which is a dependency for `rails_admin`, the gem I use that causes this for me) triggers a deprecation warning for this method in Rails5

**Comment by jasnow** [comment]
I'm getting this warning too during "rake" for this repo: https://github.com/jasnow/adopt-a-hydrant5edge

**Comment by mshibuya** [comment]
Fixed by 88d9a7d55bde66acb6cf3a3c6036a5a1fc991d5e.
