### ISSUE TITLE
Does this gem can support rails 5? 

### ISSUE THREAD

**Issue by Chaniel** [JangoSteve/remotipart#155]

**Comment by Chaniel** [comment]
when I use rails 5
.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:108:in `assert_index': No such middleware to insert after: ActionDispatch::ParamsParser (RuntimeError)

**Comment by dhrubomoy** [comment]
I am getting the same error. Looks like this GEM hasn't been upgraded for rails 5.

**Comment by dhrubomoy** [comment]
Following [this comment](https://github.com/JangoSteve/remotipart/issues/139#issuecomment-183557690), I will be temporarily using this:
`gem 'remotipart', github: 'mshibuya/remotipart', ref: '88d9a7d'`
Its working for me.

**Comment by roneen31** [comment]
@dhrubomoy Thank you. I landed here because apparently the solution I was using for some months now stopped working. I was using `ref: '3a6acb3'` but changing to `ref: '88d9a7d'` seems to work.

**Comment by sr3d** [comment]
try my fork:  https://github.com/sr3d/remotipart with the latest fixes for Rails 5.  

Note:  I had to re-add the <textarea> wrapper for the code to work properly, essentially undoing this commit:  https://github.com/sr3d/remotipart/commit/c08d61137ee18e0e78eb3cd9ca3030479fd101f1

**Comment by mshibuya** [comment]
@JangoSteve Hello, I definitely need new release in order to make [RailsAdmin](https://github.com/sferik/rails_admin) Rails 5 compatible. Merging PRs #151 and #157 would be sufficient.

Do you have time to handle it? Need some help for maintenance?

**Comment by mshibuya** [comment]
Just released 1.3.0 🚢

**Comment by SantoshTrabol** [comment]
gem 'remotipart', github: 'mshibuya/remotipart', ref: '88d9a7d' not working for me?
What is the substitute for this? When can this issue will get resolved?

**Comment by mshibuya** [comment]
Use the latest release 1.3.1.

**Comment by SantoshTrabol** [comment]
gem 'remotipart', '~> 1.3', '>= 1.3.1'
If I use the above I am getting the error i.e "fatal (exception reentered)"

**Comment by mrhamidraza** [comment]
@SantoshTrabol or anyone else: this is not working for me I am using 1.3.1 and rails 5.1, can anyone please help me? thanks

**Comment by KodyKendall** [comment]
I'm getting a similar error, which is confusing. 

After adding `gem 'remotipart', '~> 1.2'` to my Gemfile, and running `bundle install`, when I run my app I get: 

`Completed 500 Internal Server Error in 684ms (ActiveRecord: 94.0ms)
fatal (exception reentered):
UncaughtThrowError: uncaught throw :app_exception`

With a stacktrace of: 

```
UncaughtThrowError: uncaught throw :app_exception
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/web-console-3.7.0/lib/web_console/middleware.rb:137:in `throw'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/web-console-3.7.0/lib/web_console/middleware.rb:137:in `rescue in call_app'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/web-console-3.7.0/lib/web_console/middleware.rb:134:in `call_app'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/web-console-3.7.0/lib/web_console/middleware.rb:30:in `block in call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `catch'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `block in call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/webpacker-3.5.5/lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
	from /Users/kody/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

I've found that other people have seen this issue with wickedpdf in rails 5, here's a link talking about the issue: https://stackoverflow.com/questions/60683842/uncaughtthrowerror-uncaught-throw-app-exception

What's interesting is they mention that they get the same error: 

`UncaughtThrowError: uncaught throw :app_exception from /.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/web-console-3.7.0/lib/web_console/middleware.rb:137:in `throw'`.

Which is why I'm wondering if it has something with the wickedpdf gem as well. 

However, I only see this error when I try using remotipart in my project. 

Rails: Rails 5.2.2
Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
