### ISSUE TITLE
Re-submited form missing file

### ISSUE THREAD

**Issue by skyksandr** [JangoSteve/remotipart#156]
Scenario to reproduce:
- Click link - the form loaded from server
- Fill form with incorrect data but with right file
- Click submit button and get errors
- Fill with correct data and click again.

The first click request:
Processing by Events::EventTracksController#create as JS
`Parameters: {"utf8"=>"✓", "display_raw_results"=>"false", "event_track"=>{"competitor_id"=>"85", "round_id"=>"44", "track_from"=>"from_file", "track_id"=>"", "track_attributes"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0055dc644a2518 @tempfile=#<Tempfile:/tmp/RackMultipart20160804-1-oztmcn.JPG>, @original_filename="IMG_2400.JPG", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"event_track[track_attributes][file]\"; filename=\"IMG_2400.JPG\"\r\nContent-Type: image/jpeg\r\n">}}, "commit"=>"Save", "remotipart_submitted"=>"true", "authenticity_token"=>"GlYlOqMIlBK7Gdmt5Zw93QTK9cm20mowL6TZjqvZq0tAVquTlMiwreVfb0sXalxcqBkEpUZguuRlC33FqAHWqg==", "X-Requested-With"=>"IFrame", "X-Http-Accept"=>"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01", "locale"=>"ru", "event_id"=>"12"}`

The second click request:
`Parameters: {"utf8"=>"✓", "display_raw_results"=>"false", "event_track"=>{"competitor_id"=>"85", "round_id"=>"44", "track_from"=>"from_file", "track_id"=>""}, "commit"=>"Сохранить", "locale"=>"ru", "event_id"=>"12"}`

Can't figure out why it's working this way. Why file field gets cleared and not restored after getting error?
Could you please help with my issue?

**Comment by skyksandr** [comment]
I've digged a bit and found, that file getting missed on this line: https://github.com/JangoSteve/remotipart/blob/master/vendor/assets/javascripts/jquery.iframe-transport.js#L174

But I don't know why `files.appendTo(form)` make changes to original form.

**Comment by nongdenchet** [comment]
Hi @skyksandr I am trying to hack around it, can you take a look?? https://github.com/JangoSteve/remotipart/pull/159/files

**Comment by skyksandr** [comment]
@nongdenchet I've solved the issue by placing latest version of jquery.iframe-transport to my `vendor/javascripts/remotipart` with current `jquery.remotipart`. the only changes I made:
