### ISSUE TITLE
jQuery3 compatibility

### ISSUE THREAD

**Issue by spdawson** [JangoSteve/remotipart#161]
Remotipart is causing a double PATCH request in my app, following upgrade to version 1.3.0. Similar to #129 

One PATCH request contains all expected parameters, and has JavaScript format. The other PATCH has HTML format, and does not contain the attachment file parameter.

Furthermore, the spurious PATCH request does not contain the CSRF authenticity token, which is causing my application to terminate the user session as a security precaution.

I observe that if I revert commit 5366076cfd64fc00f937de13ad5fbe44dbff3262, then the problem goes away. I am using jQuery 3, which [appears](https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax) to have removed the `complete` method from the jqXHR object.

**Comment by thomasstephane** [comment]
Thanks @spdawson I have the same issue and your MR is addressing that well, anything blocking it to be merged in master?

**Comment by blackham** [comment]
+1 to the the error:
`$.rails.ajax(...).complete is not a function`

Quick fix was dropping back to jquery2.

**Comment by existent-co-uk** [comment]
+1, and dropping back to jQuery2 is not an option for our use case

**Comment by fzingg** [comment]
+1 Double Patch request with JQuery 3

**Comment by howells** [comment]
+1

**Comment by jaybloke** [comment]
+1

**Comment by adisos** [comment]
+1

**Comment by rodrei** [comment]
I'm having the same issue here

**Comment by pnaponoceno** [comment]
+1

**Comment by capjuancode** [comment]
Same here,

<%= semantic_form_for([blah, blah], remote: true ) do |f| %>

The first Request is Controller#create as JS works but I have the same TypeError:
Uncaught TypeError: $.rails.ajax(...).complete is not a function

Second Request Controller#create as HTML, because I don't have a handler for HTML 💥

is because of jQuery3 can't downgrade :( .
