### ISSUE TITLE
File Upload fields disappear on form validation failure

### ISSUE THREAD

**Issue by ankitjain200292** [JangoSteve/remotipart#185]
If I have multiple files on the same form and on validation fails it is removing the file fields from the form. EX: If i have 3 files on the form and validation field it will remove the 1 file field and 2 file fields will be present and if again validation fails then the 1 file field will be visible.

Please let me know in case anybody else facing the issue and any help is much appreciated.

Banner image field gone after validation fails.
![screenshot from 2017-10-31 17 38 58](https://user-images.githubusercontent.com/5794971/32225666-124005bc-be6c-11e7-8ac9-759c0f9a56c1.png)

**Comment by znz** [comment]
I think this is fixed in https://github.com/JangoSteve/remotipart/pull/178 .
But it have not released yet.

**Comment by ankitjain200292** [comment]
Thanks for the help @znz
