### ISSUE TITLE
With web-console

### ISSUE THREAD

**Issue by kntmrkm** [JangoSteve/remotipart#194]
I got this error when upgraded from 1.3.1 to 1.4.0

```
ActionView::Template::Error: ActionView::Helpers::ControllerHelper#params delegated to controller.params, but controller is nil
```

any relation?

**Comment by mshibuya** [comment]
Not sure, can you paste full stack trace?

**Comment by kntmrkm** [comment]
https://github.com/kntmrkm/rails51/tree/remotipart

Above repo can reproduce.

**Comment by mshibuya** [comment]
Fixed now, thanks for reporting!

**Comment by mshibuya** [comment]
https://github.com/JangoSteve/remotipart/issues/139#issuecomment-388179611
@joshkestenberg Can you upload whole error messages to gist or somewhere?
