### ISSUE TITLE
Not compatible with active_scaffold

### ISSUE THREAD

**Issue by ibotty** [JangoSteve/remotipart#202]
Using `active_scaffold` and `remotipart` together yields a SystemStackError: stack level too deep:

```
active_scaffold-3.5.2/lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render'
remotipart-1.4.2/lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
active_scaffold-3.5.2/lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render'
remotipart-1.4.2/lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
active_scaffold-3.5.2/lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render'
remotipart-1.4.2/lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
[...]
```

See
https://groups.google.com/forum/#!topic/activescaffold/Aqpcb0THyK0
for a discussion and a possible way forward.  It says one should replace `alias` with `prepend`.

**Comment by prakash-subramani** [comment]
I too have this problem. Any update?

**Comment by silambarasanmkce** [comment]
recommend an alternate solution for using remotipart in rails 5

**Comment by JangoSteve** [comment]
Can anyone verify this is still an issue with the `master` branch of this repo? The google groups thread linked says it's using remotipart v 1.3.1 which is an old version.

**Comment by silambarasanmkce** [comment]
i'm installed the gem in the master branch **(version 1.4.3)**
as
gem 'remotipart', :git => 'git://github.com/JangoSteve/remotipart.git', :branch => 'master'

and it's still showing the same error

**stack level too deep excluded from capture: DSN not set
  
SystemStackError (stack level too deep):**

**Comment by mshibuya** [comment]
Just pushed 7092d4f, please try with the master branch.

```ruby
gem 'remotipart', github: 'JangoSteve/remotipart'
```

**Comment by prakash-subramani** [comment]
It's working. Thanks!
