### ISSUE TITLE
response isn't parsed as js - mime type issue?

### ISSUE THREAD

**Issue by christopherstyles** [JangoSteve/remotipart#46]
I'm running Rails (3.2.8), jquery-rails (2.1.3) and remotipart (1.0.2). Any time I have a file upload in the form I receive the response, but it isn't parsed as javascript - in my inspector I receive the following:

`Resource interpreted as Document but transferred with MIME type text/javascript:`

I'm also not receiving an 'ajax:success' event. It's returning a 200, the post is submitted, file is saved etc. Out of ideas here...

**Comment by chrisbloom7** [comment]
I'm seeing this issue again with remotipart 1.2.1 on Rails 4.1.13. We are not using `wicked_pdf` gem. Same exact error message in the javascript console:

    Resource interpreted as Document but transferred with MIME type text/javascript

The request does not appear under the XHR filter in the Network tab of Chrome's inspector, but appears instead under the "Doc" filter.

**Request Headers**

    POST /en/vehicles/4/documents HTTP/1.1
    Host: my-app.com
    Connection: keep-alive
    Content-Length: 43239
    Pragma: no-cache
    Cache-Control: no-cache
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Origin: https://my-app.com
    Upgrade-Insecure-Requests: 1
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
    Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1t9XgVh0o2ciRyI5
    DNT: 1
    Referer: https://my-app.com/en/vehicles/4/edit
    Accept-Encoding: gzip, deflate
    Accept-Language: en-US,en;q=0.8

**Request Payload**

    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="utf8"

    ✓
    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="document[description]"

    Test 5
    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="remotipart_submitted"

    true
    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="authenticity_token"

    dO1/D8olygxGDQ+b8MuV19bSuln3Yer7ndY9U8owMFs=
    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="X-Requested-With"

    IFrame
    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="X-Http-Accept"

    text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
    ------WebKitFormBoundary1t9XgVh0o2ciRyI5
    Content-Disposition: form-data; name="document[document]"; filename="futurama-professor-good-news-everyone.jpg"
    Content-Type: image/jpeg


    ------WebKitFormBoundary1t9XgVh0o2ciRyI5--

**Response Headers**

    HTTP/1.1 200 OK
    Server: Cowboy
    Connection: close
    Date: Tue, 24 Nov 2015 19:02:40 GMT
    Status: 200 OK
    Strict-Transport-Security: max-age=31536000
    X-Frame-Options: SAMEORIGIN
    X-Xss-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Cache-Control: no-cache, no-store, max-age=0, must-revalidate
    Pragma: no-cache
    Expires: Fri, 01 Jan 1990 00:00:00 GMT
    Content-Type: text/javascript; charset=utf-8

**Response Body**

    $('#modal-dialog').modal('hide');
    $("<tr class=\"document-23\">\n  <td>\n    <p class=\"form-control-static\">\n      November 24, 2015 12:02\n    <\/p>\n  <\/td>\n  <td>\n    <p class=\"form-control-static\">\n      <a data-remote=\"true\" href=\"/en/vehicles/4/documents/23/edit\">Test 5<\/a>\n    <\/p>\n  <\/td>\n  <td>\n    <p class=\"form-control-static\">\n      41.2 KB\n    <\/p>\n  <\/td>\n  <td>\n      <a class=\"btn btn-danger btn-sm pull-right\" data-confirm=\"Are you sure you want to delete this document?\" data-method=\"delete\" data-remote=\"true\" href=\"/en/vehicles/4/documents/23\" rel=\"nofollow\">X<\/a>\n  <\/td>\n<\/tr>").hide().appendTo('#documents-table tbody').slideDown('slow');

**Comment by chrisbloom7** [comment]
This was working at one point. Since then, only 3 gems have been added. Two of them have nothing to do with rendering. The last one is NewRelic, which doesn't override the render method under Rails 4 though it does attach itself to the render event. I am wondering if that is causing the conflict?

**Comment by bbetter** [comment]
is this issue solved
reproduced for me now.
