### ISSUE TITLE
Need hook for completed request

### ISSUE THREAD

**Issue by VorontsovIE** [JangoSteve/remotipart#82]
Currently one can handle completed request, but after that remotipart makes some things to a form. I was looking for a way to change form action path (from `#create` to `#update`) after form was successfully sent, but found that after a set a path, remotipart sets old path. So it'll be nice to have a hook for a moment when form was already restored

**Comment by mshibuya** [comment]
Implemented by 5366076cfd64fc00f937de13ad5fbe44dbff3262.
