### ISSUE TITLE
Bug: Remote javascript with &quot; is not executed

### ISSUE THREAD

**Issue by dhampik** [JangoSteve/remotipart#89]
I'm using remotipart gem in conjuction with nested_form gem.
And javascript response from the server (which is inside form.js.erb) is not executed.

I studied how remotipart works and did a lot of debugging and found out the root of evil.
Unfortunately I don't know how to fix it.

So, here is the case:

```
$('.form-wrapper').html("<div data-sample=\"&lt;div id=&quot;test&quot;&gt;&lt;/div&gt;\"></div>");
```

The above javascript response from the server will not be executed on the client! Because there is `&quot;` symbol!

And this is exactly what happens if you are using remotipart+nested_form. Nested form gem produces a piece of html with data-attribute on hidden div which contains the template for newly created items which added with javascript. And this template contains `&quot;` symbol.

Why this is happening with remotipart?
I guess, because it wraps actual javascript in `<textarea>` tag and when this textarea contents are extracted by javascript the `&quot;` symbols are converted into "

**Comment by pineapple-thief** [comment]
I like panSarin solution, thank you! less code than gsub, not sure about perfomance though. I really hope this nasty glitch will be fixed in future version of remotipart.

**Comment by randoum** [comment]
@JangoSteve you haven't participated to this conversation since 2013, are you still participating to remotipart? Thanks in advance

**Comment by JangoSteve** [comment]
@randoum You're right, life seems to be getting in the way. Is there a pull request anyone has submitted for this that I could look at and merge in?

**Comment by randoum** [comment]
@JangoSteve  Nop there's no pull request, I was about to submit one, then I decided to go another direction.
Anyhow, what about finding a collaborator to second you, someone that could spend a little time on the project?
Cheers

**Comment by JangoSteve** [comment]
That would be awesome, if anyone wants to volunteer.

**Comment by JangoSteve** [comment]
*I should mention, I do have someone else who's helping maintain the project, though I think they got a bit busy themselves. Looks like @esbanarango is back in action :smile:

**Comment by esbanarango** [comment]
@randoum Could you go ahead and make that PR? I'll check as soon as possible.

**Comment by randoum** [comment]
Sorry @esbanarango I already migrated my code to use another solution, so I don't have an experimentation zone anymore

**Comment by SenikTony** [comment]
```javascript
$('.form-wrapper').html("<%= j "#{render('form')}" %>");
```
This solution worked well for me. 
Many thanks!

**Comment by sealocal** [comment]
+1 for string interpolation:

    .html("<%= j "#{render('form')}" %>");

**Comment by trkrameshkumar** [comment]
Thanks guys, this workes

``$('.response_block').html("<%= j "#{render('some_partial')}" %>");``

**Comment by westonganger** [comment]
My initial solution was the following

``` javascript
<% if remotipart_submitted? %>
  $(".form-wrapper").html("<%= j "#{render 'form' %>");
<% else %>
  $(".form-wrapper").html("<%= j render 'form' %>");
<% end %>
```

Which led me to the creation of the following monkey patch:

```ruby
# config/initializers/remotipart_escape_javascript_patch.rb

if defined?(Remotipart)

  module Remotipart
    module EscapeJavascriptFix
 
      def escape_javascript(javascript)
        if remotipart_submitted?
          super("#{javascript}")
        else
          super
        end
      end

      alias_method :j, :escape_javascript

    end
  end

  ActiveSupport.on_load :action_view do
    ActionView::Base.send(:include, Remotipart::EscapeJavascriptFix)
  end
end
```

Now you can simply do:

``` javascript
$(".form-wrapper").html("<%= j render 'form' %>");
```

I would be happy to make a PR for this. Also if help is needed for maintaining this plugin I am interested.

**Comment by rileys** [comment]
For anyone else using `escape_utils` gem this causes an issue where the data returned is not html safe.  Removed escape_utils and works fine.
