### ISSUE TITLE
Textarea wrapped around JS on initial submit

### ISSUE THREAD

**Issue by netwire88** [JangoSteve/remotipart#98]
I have jquery-rails 3.0.4 and remotipart 1.2.1. When I submit the ajax form the first time, I see textarea wrapped around the return JS (i'm returning a .js.erb file). However, if I press submit again, then the returned JS doesn't have textarea wrapped around it. How can I solve this?

Here's the wrapped data:
```
<html><body><textarea data-status='200' data-statusText='OK' data-type='text/html'><textarea data-type="text/javascript" data-status="200" data-statusText="OK">
My JS data
...
</textarea></textarea></body></html>
```

**Comment by pineapple-thief** [comment]
+1, wrapping render call into interpolated string helps, but it's pretty ugly workaround

**Comment by magicmarkker** [comment]
+1 just found this bug in production

**Comment by chrisbloom7** [comment]
Currently being bit by this as well. Is there an ETA on a patch for this?

**Comment by magicmarkker** [comment]
Is this repo even managed anymore?

**Comment by raventid** [comment]
@magicmarkker, it is managed by @esbanarango and looks like he is always here, but I have no idea why he is not updating project :cat: @esbanarango, please, merge, I am waiting for this patch too :smile:

**Comment by JangoSteve** [comment]
Hey guys, sorry for all the hold up. If @esbanarango doesn't come back to check out the patch soon, I'll try to take a look or get someone who can.

**Comment by esbanarango** [comment]
@JangoSteve Checking this now.

**Comment by guilhermeyo** [comment]
+1
